---
- name: Install packages
  apt:
    update_cache: yes
    state: latest
    pkg:
    - bzip2
    - emacs-nox
    - expect
    - gdb
    - consolation
    - htop
    - hwinfo
    - jq
    - lvm2
    - nano
    - ncdu
    - p7zip
    - parted
    - qrencode
    - rsync
    - strace
    - tig
    - tmux
    - vim-nox
    - xz-utils

- name: Support right-button clipboard pasting
  lineinfile:
    dest: /etc/default/consolation
    create: yes
    regexp: 'DAEMON_OPTS=""'
    line: 'DAEMON_OPTS="--map BTN_RIGHT=paste"'

- name: Install Yubico management utils
  # This is needed because debian buster repo's don't include this anymore
  block:
  - apt:
      deb: http://ftp.us.debian.org/debian/pool/main/y/yubico-piv-tool/libykpiv2_2.2.0-1_amd64.deb
  - apt:
      deb: http://ftp.us.debian.org/debian/pool/main/y/yubico-piv-tool/yubico-piv-tool_2.2.0-1_amd64.deb
