---
- name: Install packages
  apt:
    update_cache: yes
    state: latest
    pkg:
    - libftdi-dev
    - libhidapi-libusb0
    - libusb-1.0-0
    - libusb-1.0-0-dev
    - scdaemon
    - libudev-dev
    - libhidapi-dev
    - yubikey-personalization
    - libccid
    - libchipcard-tools
    - libchipcard-data
    - libpcsclite1
    - pcscd
    - python3-pyscard
    - python3-dev

- name: Create udev rule to auto-detect Yubikey insertion
  block:
    - template:
       src: insert-yubi.sh
       dest: /usr/local/bin/
       mode: "0744"
    - template:
       src: 69.yubikey.rules
       dest: /etc/udev/rules.d/
       mode: "0644"
    - shell: "udevadm control -R"
      become: yes
