---
- name: Install APT packages
  apt:
    update_cache: yes
    state: latest
    pkg:
    - gnupg
    - gnupg2
    - dirmngr
    - pinentry-tty
    - scrypt
    - ssdeep
    - seccure
    - ssl-cert
    - openssl
    - gnutls-bin
    - monkeysphere
    - pgpgpg
    - signing-party
    - gpgv
    - gpgv2
    - x509-util
    - keyanalyze
    - pgpdump
    - keyutils
    - pius

- name: Airgap MOTD timedrift warning
  block:
  - template:
      src: timecheck-motd.sh
      dest: /etc/update-motd.d/100-timecheck
      mode: "0755"
  - file:
      path: /etc/motd
      state: absent

