---
- name: Remove build dependencies
  apt:
    state: absent
    pkg:
    - build-essential
    - autoconf
    - automake
    - libtool
    - libgl1-mesa-dri
    - adwaita-icon-theme
    - libgtk-3-common
    - libgtk2.0-common
    - libc6-dbg
    - "x11-*"

- name: Cleanup Cruft files
  action: file state=absent path={{item}}
  with_items:
    - "/var/cache/apt/"
    - "/var/cache/debconf/"
    - "/var/lib/mysql/"
    - "/var/lib/apt/"
    - "/var/log/"
    - "/usr/share/doc/"
    - "/usr/share/icons/"
    - "/home/{{ user }}/.ansible"

- name: Trim Filesystem
  shell: fstrim -av
